### ISSUE TITLE
wc,我找到组织了

### ISSUE THREAD

**Issue by TXIuTnVsbA** [CelestialTS/CSGO-Internal-Hack#1]
大佬你好

**Comment by CelestialPaler** [comment]
你好2333，代码很搓，欢迎提出宝贵建议。

**Comment by TXIuTnVsbA** [comment]
> 你好2333，代码很搓，欢迎提出宝贵建议。

我感觉你写的应该是外部挂,不是内部挂好像,uc上面有人说过,来吧一起耍内部挂吧,我观察了很久,内部挂都把起源的源码拿来用的,好像是把已经建立好的东西拿来用,= =虽然我也是这么做,但我是copy的= =好多都不懂

**Comment by TXIuTnVsbA** [comment]
> 你好2333，代码很搓，欢迎提出宝贵建议。

做暴力挂不咯,拿来玩hvh

**Comment by CelestialPaler** [comment]
是这样的，我这个虽然是内部挂，但是其实没用充分利用内部挂的优势，那就是可以调用游戏自己的各种函数，这样可以实现很多厉害的功能，我这个只是从内部像外部挂一样读取数据，实现的方式比较像外部。把起源源码拿来一起就是为了方便调用游戏与引擎的内部函数。这个我也在摸索。

**Comment by CelestialPaler** [comment]
HvH太猛了，干不过😂。

**Comment by TXIuTnVsbA** [comment]
> HvH太猛了，干不过。

没事阿,hvh再怎么猛也就那样子嘛= =研究研究开源的挂,再改改还是可以的
