### ISSUE TITLE
可能存在的bug

### ISSUE THREAD

**Issue by ghost** [CelestialTS/CSGO-Internal-Hack#2]
https://github.com/CelestialTS/CSGO-Internal-Hack/blob/328158ead18438bf0e68906968d1f61d9f5ad67c/CSGO-Internal-Hack-Dll/main.h#L137
如果别的用户不存在这一路径呢?

**Comment by CelestialPaler** [comment]
> https://github.com/CelestialTS/CSGO-Internal-Hack/blob/328158ead18438bf0e68906968d1f61d9f5ad67c/CSGO-Internal-Hack-Dll/main.h#L137
> 
> 
> 如果别的用户不存在这一路径呢?

嗯嗯，首先谢谢指出问题。
所有的文件路径等都暂时是绝对路径，主要还是因为现在还在开发，一些游戏文件例如SkinID和一些Offset等都是第三方来源的数据，临时存放使用，之后应该会弄个配置文件，可以对外挂的路径和其它参数进行配置，比如config.json啥的。并且将一些dumper整合进来，使这些第三方数据随游戏能自动更新。是个很重要的问题，这个issue放在这可以作为备忘。
谢谢~

**Comment by ghost** [comment]
其实我觉得skinid可以通过 [这个办法](https://www.unknowncheats.me/forum/counterstrike-global-offensive/223079-fast-fileless-sticker-kit-paint-kit-dumper-pastable.html) 给dump出来,这样也无需文件了

**Comment by CelestialPaler** [comment]
> 其实我觉得skinid可以通过 [这个办法](https://www.unknowncheats.me/forum/counterstrike-global-offensive/223079-fast-fileless-sticker-kit-paint-kit-dumper-pastable.html) 给dump出来,这样也无需文件了

原本是打算从..\Counter-Strike Global Offensive\csgo\scripts\items\items_game.txt这个文件直接parse，这里面有所有的Skin信息，但是好像没有贴纸信息。
你发这个看起来不错，回头研究下。
