### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by ghost** [CelestialTS/CSGO-Internal-Hack#3]
Game instantly crashes after injecting "CSGO-Internal-Hack-Dll.dll" and there is no injector exe in the files.

**Comment by Nacorpio** [comment]
The injector can be downloaded [here](https://github.com/nefarius/Injector/releases).
As for the game crashes, I have the same issue.

**Comment by CelestialPaler** [comment]
Firstly, thank you for pointing out the problem.
So that is the same issue I`ve been struggling a lot, sometimes it crashed when I enable some features, which is caused by nullptr dereferencing, but the game never crashes instantly after injecting "CSGO-Internal-Hack-Dll.dll".
Can you guys give me more info about the crash? Such as system environments or any warning when injecting.
And make sure to inject **Indicium-Supra.dll** first, then inject **CSGO-Internal-Hack-Dll.dll**.
As for the injector, you can choose any injector you like, or you can download the injector from nefarius/Injector repo.

**Comment by Nacorpio** [comment]
> 
> 
> Firstly, thank you for pointing out the problem.
> So that is the same issue I`ve been struggling a lot, sometimes it crashed when I enable some features, which is caused by nullptr dereferencing, but the game never crashes instantly after injecting "CSGO-Internal-Hack-Dll.dll".
> Can you guys give me more info about the crash? Such as system environments or any warning when injecting.
> And make sure to inject **Indicium-Supra.dll** first, then inject **CSGO-Internal-Hack-Dll.dll**.
> As for the injector, you can choose any injector you like, or you can download the injector from nefarius/Injector repo.

I am currently running Windows 10, but there is not much information to give about the crash.
It says that the module was injected successfully, then once you maximize the game it just crashes.

**Comment by CelestialPaler** [comment]
> > Firstly, thank you for pointing out the problem.
> > So that is the same issue I`ve been struggling a lot, sometimes it crashed when I enable some features, which is caused by nullptr dereferencing, but the game never crashes instantly after injecting "CSGO-Internal-Hack-Dll.dll".
> > Can you guys give me more info about the crash? Such as system environments or any warning when injecting.
> > And make sure to inject **Indicium-Supra.dll** first, then inject **CSGO-Internal-Hack-Dll.dll**.
> > As for the injector, you can choose any injector you like, or you can download the injector from nefarius/Injector repo.
> 
> I am currently running Windows 10, but there is not much information to give about the crash.
> It says that the module was injected successfully, then once you maximize the game it just crashes.

recently, i try to use the hack in many other computers, and it seems the hack is vary instable, sometimes it crash the game, sometimes it can not be injected into the game correctly, which seems is about **LoadLibraryW()**, and the hack also works for few times. So i`ll try to setup some tests in different environment to check the error code and the exit code in order to debug the problem.

**Comment by Nacorpio** [comment]
> 
> 
> > > Firstly, thank you for pointing out the problem.
> > > So that is the same issue I`ve been struggling a lot, sometimes it crashed when I enable some features, which is caused by nullptr dereferencing, but the game never crashes instantly after injecting "CSGO-Internal-Hack-Dll.dll".
> > > Can you guys give me more info about the crash? Such as system environments or any warning when injecting.
> > > And make sure to inject **Indicium-Supra.dll** first, then inject **CSGO-Internal-Hack-Dll.dll**.
> > > As for the injector, you can choose any injector you like, or you can download the injector from nefarius/Injector repo.
> > 
> > 
> > I am currently running Windows 10, but there is not much information to give about the crash.
> > It says that the module was injected successfully, then once you maximize the game it just crashes.
> 
> recently, i try to use the hack in many other computers, and it seems the hack is vary instable, sometimes it crash the game, sometimes it can not be injected into the game correctly, which seems is about **LoadLibraryW()**, and the hack also works for few times. So i`ll try to setup some tests in different environment to check the error code and the exit code in order to debug the problem.

Alright, sounds good man.
Let me know if I can assist you in any way.

**Comment by ghost** [comment]
> > > Firstly, thank you for pointing out the problem.
> > > So that is the same issue I`ve been struggling a lot, sometimes it crashed when I enable some features, which is caused by nullptr dereferencing, but the game never crashes instantly after injecting "CSGO-Internal-Hack-Dll.dll".
> > > Can you guys give me more info about the crash? Such as system environments or any warning when injecting.
> > > And make sure to inject **Indicium-Supra.dll** first, then inject **CSGO-Internal-Hack-Dll.dll**.
> > > As for the injector, you can choose any injector you like, or you can download the injector from nefarius/Injector repo.
> > 
> > 
> > I am currently running Windows 10, but there is not much information to give about the crash.
> > It says that the module was injected successfully, then once you maximize the game it just crashes.
> 
> recently, i try to use the hack in many other computers, and it seems the hack is vary instable, sometimes it crash the game, sometimes it can not be injected into the game correctly, which seems is about **LoadLibraryW()**, and the hack also works for few times. So i`ll try to setup some tests in different environment to check the error code and the exit code in order to debug the problem.

Well tbf I used extreme injector to inject cause I couldn't find the loader, wasn't included anywhere so that might be reason for the crash when injecting.

**Comment by ghost** [comment]
Update: I injected using ur method of injection and CS crashed instantly so I guess I wasn't wrong.
