### ISSUE TITLE
作弊器会导致游戏崩溃

### ISSUE THREAD

**Issue by tylk520** [CelestialTS/CSGO-Internal-Hack#4]
你好，进入游戏开启作弊器后，作弊器所有功能都不能正常使用，而且还会导致游戏崩溃。请问是不是因为作弊器不能在现在的版本使用了？您有现在版本可以用的作弊器吗，我这边需要录制一个搞笑视频，需要用到您的作弊器，我只会在机器人练习模式中使用（因为我也怕封号），不会影响到其他玩家。

**Comment by CelestialPaler** [comment]
> 你好，进入游戏开启作弊器后，作弊器所有功能都不能正常使用，而且还会导致游戏崩溃。请问是不是因为作弊器不能在现在的版本使用了？您有现在版本可以用的作弊器吗，我这边需要录制一个搞笑视频，需要用到您的作弊器，我只会在机器人练习模式中使用（因为我也怕封号），不会影响到其他玩家。

你好，
是这样的，这个作弊器已经很久未更新与维护了，已经无法使用了。我也这边没有能够使用的版本可以提供。
如果需要外挂的话，Github上的一般都是零零散散的外挂，大部分都很难直接使用。你可以在一些论坛里找到最新的可以使用的成品外挂，能够线下使用的外挂非常多，并且这些外挂的功能会更加全面与稳定，可能为你的搞笑视频提供更多有意思的素材。
[https://www.unknowncheats.me/forum/index.php](url)
[https://guidedhacking.com/](url)

**Comment by tylk520** [comment]
万分感谢，您的回复帮我了大忙

Celestial Paler <notifications@github.com> 于2019年12月1日周日 上午11:35写道：
